"""Data models and transfer objects conforming to OpenSpec specifications."""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import List, Optional


class SyncActionType(str, Enum):
    """Types of sync actions generated by reconciliation."""
    GRANT = "GRANT"
    REVOKE = "REVOKE"
    NO_OP = "NO_OP"


@dataclass(frozen=True)
class Subscriber:
    """Represents a Substack subscriber record."""
    email: str
    subscription_type: str  # paid, comp, founding, gift, free, etc.
    status: str  # active, canceled, expired, etc.
    expiry: Optional[datetime] = None
    created_at: Optional[datetime] = None

    @property
    def is_paid_active(self) -> bool:
        """Determines if the subscriber is qualified for paid indicator access."""
        sub_type = self.subscription_type.strip().lower()
        sub_status = self.status.strip().lower()

        # Check paid subscription tier
        valid_tiers = {"paid", "comp", "founding", "gift"}
        if sub_type not in valid_tiers:
            return False

        # Inactive statuses
        inactive_statuses = {"canceled", "expired", "inactive", "refunded"}
        if sub_status in inactive_statuses:
            # If an expiration timestamp is in the future, access is still active
            if self.expiry and self.expiry > datetime.now(self.expiry.tzinfo):
                return True
            return False

        return True


@dataclass(frozen=True)
class FormResponse:
    """Represents a Google Form submission row."""
    submitted_at: datetime
    email: str
    tradingview_username: str

    @classmethod
    def create_normalized(cls, submitted_at: datetime, email: str, username: str) -> "FormResponse":
        """Creates a FormResponse with normalized email and TradingView username."""
        clean_email = email.strip().lower()
        clean_username = username.strip().lstrip("@")
        return cls(
            submitted_at=submitted_at,
            email=clean_email,
            tradingview_username=clean_username
        )


@dataclass(frozen=True)
class TradingViewUser:
    """Represents a user currently authorized on TradingView's invite-only list."""
    username: str
    user_id: Optional[int] = None
    expiration: Optional[str] = None  # None for permanent/ongoing
    has_access: bool = True


@dataclass
class SyncAction:
    """A single pending grant or revoke action."""
    action_type: SyncActionType
    tradingview_username: str
    email: Optional[str] = None
    reason: str = ""


@dataclass
class DiffPlan:
    """The complete diff execution plan generated by the reconciliation engine."""
    grants: List[SyncAction] = field(default_factory=list)
    revokes: List[SyncAction] = field(default_factory=list)
    no_ops: List[SyncAction] = field(default_factory=list)
    unregistered_paid_subscribers: List[str] = field(default_factory=list)
    unmatched_form_submissions: List[FormResponse] = field(default_factory=list)

    @property
    def has_changes(self) -> bool:
        """Returns True if there are pending grants or revocations."""
        return len(self.grants) > 0 or len(self.revokes) > 0
